displayName=GIMventory Setups
author=Robbejj
description=Extends the Inventory Setups plugin to also work in the GIM storage
tags=inventory,setups,gim,group ironman,shared bank,storage
version=
plugins=com.gimventorysetups.GIMventorySetupsPlugin
build=standard