displayName=GIMventory Setups
author=Robbejj/arrtism
description=Extends the Inventory Setups plugin to also work in GIM storage
tags=inventory,setups,gim,group ironman,shared bank,storage
version=
plugins=com.gimventorysetups.GIMventorySetupsPlugin
build=standard